#!/bin/bash

liste=()
 
parcours_dossiers()
{
	for i in *
	do
		if [ -d $i ]; then
	        	liste=( "${liste[*]}" '$i' )
	    	fi
    	done
	test=`pwd`
	for dossier in liste
	do
		cd $test/$dossier
		parcours_dico
		unset liste[0]
	done
}

#le dictionnaire est composé de lignes, chaque ligne ressemble à ça : nom_dossier,extension1,extension2...

parcours_dico(){            #cette fonction classifie le dossier pour chaque ligne
	lignes=`wc -l classement.txt` #on récupère le nombre de lignes
	for i in `seq 1 $lignes`        #et on classe (fonction classify) pour chaque ligne du dico
	do
		ligne=`cat classement.txt | awk -v i=$i 'NR == i {print;}'`
        	listeExt=()
		for mot in ligne;
			listeExt[${#listeExt[*]}]=$mot
		done
        	classify_cat
	done
}

classify_cat()
{
	for file in * 
	do 
		#tester chaque extension de la catégorie sur la commande `ls | grep -e extension`
		extension=`echo $file | sed 's/.*\.//g'`			
	        if [[ " ${listeExt[@]} " =~ " ${extension} " ]]; then #array sera la liste des extensions courantes
                	if [ ! -d $chemin/${listeExt[0]} ]; then
                		mkdir $chemin/${listeExt[0]}
            		fi
                	mv file ${listeExt[0]}/
        	fi
    	done
}

# on peut faire sh s.sh param
